swagger: '2.0'
host: swagger.io
basePath: /
info:
  title: Swagger Sample App
  description: This is a sample server Petstore server.
  termsOfService: http://swagger.io/terms/
  contact:
    name: API Support
    url: http://www.swagger.io/support
    email: support@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1

schemes:
 - https

consumes:
  - application/json

produces:
  - application/json

paths:
  /speakers:
    get:
      description: get list of speakers 
      responses:
        '200':
          description: OK
  /talks:
    get:
      description: get list of talks
      responses:
        '200':
          description: OK
  /pets:
    get:
      description: get list of pets
      responses:
        '200':
          description: OK


